### ISSUE TITLE
Admin Shop Suggestion

### ISSUE THREAD

**Issue by Shane1199** [Zerthick/PlayerShopsRPG#13]
It would be awesome to add some type of admin shop support. Currently there is nothing out there that works well for Sponge API 5 & 6. For details, it's all open I just would like to see support to have unlimited refilling and no ownership of the shops.

**Comment by Zerthick** [comment]
Shops currently support having unlimited money and stock through the [shop set unlimited](https://github.com/Zerthick/PlayerShopsRPG/wiki/Commands#shop-set-unlimited) command. Yes currently all shops must have an owner in order to function, however if you set an admin as an owner and make all other admins a manager of the shop it should work for the time being, I'm looking into allowing ownerless shops, though it will require a bit of reworking of the system.

**Comment by Zerthick** [comment]
Added in [v2.0.0](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.0)!
