### ISSUE TITLE
Not able to use the /shop item set command

### ISSUE THREAD

**Issue by Whazaaaaa** [Zerthick/PlayerShopsRPG#27]
With the latest version the command for 

> /shop item set buy/sell index amount

 does not seem to work and gives a weird error when trying: `[CHAT] Error occurred while executing command: Invalid UUID string: 0`

representation of what I did: http://recordit.co/kX5mCIJyEu

Has the command changed or is there a problem or something?

Edit: Note that it works perfectly fine when using the 'Manager' in the /shop browse and clicking on the prices to change them

**Comment by Zerthick** [comment]
Yes this is the correct behavior, indices were changed to utilize UUIDs instead of simple integers in the 2.0 release of PlayerShops, these commands were never actually intended to be run by the player directly, which is why the UI options are available.  Is there a need to not use the UI to perform these functions?

**Comment by Whazaaaaa** [comment]
The command was still in the wiki making me think the command was still valid. Its been the way alot of people used the shops before on my servers so that why I reported it(as people were asking questions why its not working anymore). Imho the manager way is much better so its perfect the way it is.
