### ISSUE TITLE
shop infos | drop shop inventar on ground when destroy

### ISSUE THREAD

**Issue by realKSMC** [Zerthick/PlayerShopsRPG#5]
Hi there,

can u add some messages even if u setup something as manager for the shop, like an message for "You have set the buy price for Bread to 5."
After setting up something for the shop, is it possible to get automatically back without type in /shop browse again? Would be great!

At least, if you destroy the shop, please add that the content drops on ground - currently the items will destroy :/

Thx and greetz,
Hannes aka. TheYololetsplay

**Comment by Zerthick** [comment]
Hey!  Yes, I definitely plan to add more messages confirming you actions, I plan to add a message file per #3 so that the Plugin will be able to be translatable!

I plan to add returning to the shop after setting something in the next update :smile:  

The reason I just simply destroy the items is because if the shop contains hundreds of items I don't want to crash the server spawning them all at once :stuck_out_tongue_winking_eye: However I do plan to add in a warning and confirmation that you indeed want to destroy a shop containing items.

**Comment by yololetsplay** [comment]
Maybe u will drop this asynchronly, every second 1 stack or so to let the server stabilize :]
